
# Habilita el soporte para I2C
CONFIG_I2C=y

# Soporte para formato flotante (útil con printf/logs)
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_DEVICE_NAME="NRF52-PROYECTO"
CONFIG_LOG=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_BT_GATT_SERVICE_CHANGED=y



# Bluetooth stack
CONFIG_BT_GATT_CLIENT=y


