
# Habilita el soporte para I2C
CONFIG_I2C=y

# Soporte para formato flotante (útil con printf/logs)
CONFIG_CBPRINTF_FP_SUPPORT=y

# Framework de sensores y driver del MAX30101
CONFIG_SENSOR=y
CONFIG_MAX30101=y

# Logging para ver mensajes del sensor en tiempo real
CONFIG_LOG=y

